### ISSUE TITLE
onlyDirectDestroy config option is unused in code

### ISSUE THREAD

**Issue by wingzero54** [CivMC/Bastion#13]
I checked all references to the config option "onlyDirectDestroy" and it is not actually used anywhere in the plugin.

**Comment by Diet-Cola** [comment]
https://github.com/CivMC/Bastion/blob/f6d0b049a181fbb6b8a2f0574ed5499144a019e8/paper/src/main/java/isaac/bastion/listeners/BastionDamageListener.java#L57

**Comment by wingzero54** [comment]
The config option is onlyDirectDestroy, the code uses isOnlyDirectDestruction. The config option isn't passed into isOnlyDirectDestruction. It is instantiated as a boolean but never given a value

**Comment by wingzero54** [comment]
The getter gets onlyDirectDestruction, not onlyDirectDestroy

**Comment by Diet-Cola** [comment]
We pass in that config option as a new `BastionType` object

When constructing the BastionType object here: https://github.com/CivMC/Bastion/blob/master/paper/src/main/java/isaac/bastion/BastionType.java#L583  

onlyDirectDestroy is passed in and saved as `onlyDirectDestruction` here: https://github.com/CivMC/Bastion/blob/master/paper/src/main/java/isaac/bastion/BastionType.java#L111
